name: Daily Reminder

on:
  schedule:
    # 12:05 PM Pakistan Time → 786 link
    - cron: '5 7 * * *'
    # 12:10 PM Pakistan Time → 787 link
    - cron: '10 7 * * *'
  workflow_dispatch:

jobs:
  hit-786:
    if: github.event.schedule == '5 7 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Hit 786 Reminder
        run: curl -L "https://nspinternet.free.nf/786-reminder.php"

  hit-787:
    if: github.event.schedule == '15 15 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Hit 787 Reminder
        run: curl -L "https://nspinternet.free.nf/787-reminder.php"
